version: '3'

networks:
    flask_app:
        driver: bridge

services:
    app_blue:
        build:
            context: ./app_blue
        networks:
            - flask_app
    app_green:
        build:
            context: ./app_green
        networks:
            - flask_app

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - "80:80"
        depends_on:
            - app_green
            - app_blue
        networks:
            - flask_app

