version: '3'
services:
    app: &web
        build:
            context: ./app

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        depends_on:
            - app