version: '3'

networks:
    flask_app:
        driver: bridge

services:
    app:
        build:
            context: ./app
        networks:
            - flask_app


    nginx:
        container_name: nginx
        build: nginx
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - flask_app

